### ISSUE TITLE
绑定用户可以，但是无法生成复读图片

### ISSUE THREAD

**Issue by MeiJuice** [gsycl2004/XXYan#2]
2022-07-10 16:18:49 E/XXYan: Exception in coroutine Plugin com.github.XXYan of XXYan
java.lang.ExceptionInInitializerError
        at XXYan-0.0.5.mirai2.jar//com.github.XXYan$onEnable$2.invokeSuspend(XXYan.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Unknown Source)
        at java.desktop/java.awt.Font.createFont(Unknown Source)
        at XXYan-0.0.5.mirai2.jar//com.github.core.MessagePainter.<clinit>(MessagePainter.kt:22)
        ... 7 more

2022-07-10 16:18:50 E/XXYan: Exception in coroutine Plugin com.github.XXYan of XXYan
java.lang.NoClassDefFoundError: Could not initialize class com.github.core.MessagePainter
        at XXYan-0.0.5.mirai2.jar//com.github.XXYan$onEnable$2.invokeSuspend(XXYan.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by MeiJuice** [comment]
yum install fontconfig 可解决java.io.IOException: Problem reading font data.
